#http
services:
  app:
    image: ghcr.io/mahn-ke/slides-by-vincent:latest
    restart: on-failure:5
    environment:
      - PORT=3000
    ports:
      - "3009:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
